def kFile = rootProject.file('local.properties')
def props = new Properties()
def signingConfig = project.extensions.getByName('android').signingConfigs.getByName('sign')
if (kFile.canRead()) {
    props.load(new FileInputStream(kFile))

    if (props != null) {
        signingConfig.storeFile = rootProject.file('composeApp').toPath().resolve(props['SIGN_KEY_STORE_FILE']).toFile()
        signingConfig.storePassword = props['SIGN_KEY_STORE_PASSWORD']
        signingConfig.keyAlias = props['SIGN_KEY_ALIAS']
        signingConfig.keyPassword = props['SIGN_KEY_PASSWORD']
    }
} else {
    signingConfig.storeFile = rootProject.file('composeApp').toPath().resolve(System.getenv('SIGN_KEY_STORE_FILE')).toFile()
    signingConfig.storePassword = System.getenv('SIGN_KEY_STORE_PASSWORD')
    signingConfig.keyAlias = System.getenv('SIGN_KEY_ALIAS')
    signingConfig.keyPassword = System.getenv('SIGN_KEY_PASSWORD')
}
